using Dapper;

namespace Awagaman.Api.DataAccess;

public sealed class PostgresSchemaInitializer
{
    private readonly IPgConnectionFactory _factory;

    public PostgresSchemaInitializer(IPgConnectionFactory factory)
    {
        _factory = factory;
    }

    public async Task EnsureCreatedAsync()
    {
        await using var conn = _factory.Create();
        await conn.OpenAsync();

        var statements = new[]
        {
            @"CREATE TABLE IF NOT EXISTS parties (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                party_name TEXT NOT NULL UNIQUE,
                address TEXT,
                gst_no TEXT
            );",
            @"CREATE TABLE IF NOT EXISTS challans (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                challan_number TEXT NOT NULL UNIQUE,
                date TIMESTAMP NOT NULL,
                lr_number TEXT,
                broker_name TEXT,
                from_location TEXT,
                to_location TEXT,
                vehicle_number TEXT,
                vehicle_type TEXT,
                driver_name TEXT,
                driver_mobile TEXT,
                engine_no TEXT,
                licence_no TEXT,
                policy_no TEXT,
                chassis_no TEXT,
                owner_name TEXT,
                pan TEXT,
                lorry_hire NUMERIC(18,2) NOT NULL DEFAULT 0,
                less_tds NUMERIC(18,2) NOT NULL DEFAULT 0,
                advance_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
                advance_neft NUMERIC(18,2) NOT NULL DEFAULT 0,
                advance_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
                advance_date TIMESTAMP NULL,
                detention NUMERIC(18,2) NOT NULL DEFAULT 0,
                hamali NUMERIC(18,2) NOT NULL DEFAULT 0,
                deduction NUMERIC(18,2) NOT NULL DEFAULT 0,
                balance_paid_neft NUMERIC(18,2) NOT NULL DEFAULT 0,
                balance_paid_cash NUMERIC(18,2) NOT NULL DEFAULT 0,
                balance_paid_date TIMESTAMP NULL,
                paid_to TEXT,
                remarks TEXT,
                bill_amount NUMERIC(18,2) NOT NULL DEFAULT 0,
                margin NUMERIC(18,2) NOT NULL DEFAULT 0
            );",
            @"CREATE TABLE IF NOT EXISTS lr_entries (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                lrno TEXT NOT NULL UNIQUE,
                date TIMESTAMP NOT NULL,
                consignor_name TEXT,
                consignor_address TEXT,
                consignor_gst TEXT,
                consignee_name TEXT,
                consignee_address TEXT,
                consignee_gst TEXT,
                from_location TEXT,
                to_location TEXT,
                vehicle_no TEXT,
                vehicle_type TEXT,
                weight NUMERIC(18,2) NOT NULL DEFAULT 0,
                size_l NUMERIC(18,2) NOT NULL DEFAULT 0,
                size_w NUMERIC(18,2) NOT NULL DEFAULT 0,
                size_h NUMERIC(18,2) NOT NULL DEFAULT 0,
                actual_weight NUMERIC(18,2) NOT NULL DEFAULT 0,
                charged_weight NUMERIC(18,2) NOT NULL DEFAULT 0,
                pkg INTEGER NOT NULL DEFAULT 0,
                pkg_type TEXT,
                description TEXT,
                invoice TEXT,
                value TEXT,
                chno TEXT,
                total_freight NUMERIC(18,2) NOT NULL DEFAULT 0,
                hamali NUMERIC(18,2) NOT NULL DEFAULT 0,
                detention NUMERIC(18,2) NOT NULL DEFAULT 0,
                others NUMERIC(18,2) NOT NULL DEFAULT 0,
                st_charge NUMERIC(18,2) NOT NULL DEFAULT 0,
                neft NUMERIC(18,2) NOT NULL DEFAULT 0,
                cash NUMERIC(18,2) NOT NULL DEFAULT 0,
                tds NUMERIC(18,2) NOT NULL DEFAULT 0,
                ded NUMERIC(18,2) NOT NULL DEFAULT 0,
                bill_no TEXT,
                bill_date TIMESTAMP NULL,
                bill NUMERIC(18,2) NOT NULL DEFAULT 0,
                bill_party TEXT,
                broker TEXT,
                frt_type TEXT,
                pay_type TEXT,
                comm NUMERIC(18,2) NOT NULL DEFAULT 0,
                paid TEXT
            );",
            @"CREATE TABLE IF NOT EXISTS bills (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                bill_no TEXT,
                bill_date TIMESTAMP NULL,
                party TEXT,
                lr_no TEXT,
                lr_date TIMESTAMP NULL,
                from_loc TEXT,
                to_loc TEXT,
                vehicle_type TEXT,
                freight NUMERIC(18,2) NOT NULL DEFAULT 0,
                detention NUMERIC(18,2) NOT NULL DEFAULT 0,
                hml NUMERIC(18,2) NOT NULL DEFAULT 0,
                othr NUMERIC(18,2) NOT NULL DEFAULT 0,
                st_charge NUMERIC(18,2) NOT NULL DEFAULT 0,
                rcvd NUMERIC(18,2) NOT NULL DEFAULT 0,
                tds NUMERIC(18,2) NOT NULL DEFAULT 0,
                ded NUMERIC(18,2) NOT NULL DEFAULT 0,
                mop TEXT,
                mr TEXT,
                remarks TEXT,
                date TIMESTAMP NULL
            );",
            @"CREATE TABLE IF NOT EXISTS cbs_accounts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                account_name TEXT NOT NULL UNIQUE,
                is_active BOOLEAN NOT NULL DEFAULT TRUE
            );",
            @"CREATE TABLE IF NOT EXISTS cash_bank_statements (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                cbs TEXT,
                date TIMESTAMP NOT NULL,
                account_name TEXT,
                particulars TEXT,
                remarks TEXT,
                bank_dr NUMERIC(18,2) NOT NULL DEFAULT 0,
                bank_cr NUMERIC(18,2) NOT NULL DEFAULT 0,
                cash_dr NUMERIC(18,2) NOT NULL DEFAULT 0,
                cash_cr NUMERIC(18,2) NOT NULL DEFAULT 0
            );",
            @"CREATE TABLE IF NOT EXISTS vehicle_ledger (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sr INTEGER NOT NULL,
                vehicle_number TEXT NOT NULL UNIQUE,
                owner_name TEXT,
                pan_number TEXT,
                engine_number TEXT,
                chassis_number TEXT,
                vehicle_type TEXT
            );",
            @"CREATE TABLE IF NOT EXISTS bill_receipts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                bill_no TEXT NOT NULL,
                party TEXT,
                bill_total NUMERIC(18,2) NOT NULL DEFAULT 0,
                bill_date TIMESTAMP NULL,
                receipt_date TIMESTAMP NOT NULL,
                rcvd NUMERIC(18,2) NOT NULL DEFAULT 0,
                tds NUMERIC(18,2) NOT NULL DEFAULT 0,
                ded NUMERIC(18,2) NOT NULL DEFAULT 0,
                mop TEXT,
                mr TEXT,
                remarks TEXT,
                due_after NUMERIC(18,2) NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL
            );"
            ,
            @"CREATE TABLE IF NOT EXISTS challan_comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                challan_id INTEGER NOT NULL,
                comment TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL
            );",
            @"CREATE TABLE IF NOT EXISTS lr_comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                lr_entry_id INTEGER NOT NULL,
                comment TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL
            );",
            @"CREATE TABLE IF NOT EXISTS bill_comments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                bill_id INTEGER NOT NULL,
                comment TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL
            );",
            @"CREATE TABLE IF NOT EXISTS reporting_tracks (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tracking_entry_id INTEGER NOT NULL,
                report_date_time TIMESTAMP NOT NULL,
                remarks TEXT
            );"
        };

        foreach (var sql in statements)
        {
            await conn.ExecuteAsync(sql);
        }

        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_parties_party_name ON parties(party_name);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_challans_challan_number ON challans(challan_number);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_lr_entries_lrno ON lr_entries(lrno);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_bills_bill_no ON bills(bill_no);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_cbs_accounts_account_name ON cbs_accounts(account_name);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_cash_bank_statements_date ON cash_bank_statements(date);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_vehicle_ledger_vehicle_number ON vehicle_ledger(vehicle_number);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_challan_comments_challan_id ON challan_comments(challan_id);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_lr_comments_lr_entry_id ON lr_comments(lr_entry_id);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_bill_comments_bill_id ON bill_comments(bill_id);");
        await conn.ExecuteAsync("CREATE INDEX IF NOT EXISTS ix_reporting_tracks_tracking_entry_id ON reporting_tracks(tracking_entry_id);");
    }
}
