using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;
using System.Windows.Media;
using Awagaman_ERP.Data;
using Awagaman_ERP.Helpers;
using Awagaman_ERP.Models;
using MahApps.Metro.Controls;

namespace Awagaman_ERP
{
    public partial class ChallanFormWindow : MetroWindow
    {
        public ChallanEntry Result { get; private set; }
        public bool WasSaved { get; private set; }
        private IEnumerable<ChallanEntry> _allEntries;
        private int _editingSr;
        private readonly IChallanRepository _repository;
        private bool _ignoreVehicleSelection;
        private bool _ignoreTextSuggestions;
        private readonly bool _isNewEntry;
        private string _lastAutoGeneratedChallanNumber = string.Empty;
        private readonly DispatcherTimer _vehicleSuggestionTimer = new DispatcherTimer { Interval = System.TimeSpan.FromMilliseconds(350) };
        private List<string> _brokerNames = new List<string>();
        private List<string> _fromPlaces = new List<string>();
        private List<string> _toPlaces = new List<string>();

        public ChallanFormWindow(IEnumerable<ChallanEntry> allEntries, IChallanRepository repository = null)
        {
            InitializeComponent();
            ConfigureDebounceTimers();
            _allEntries = allEntries ?? new List<ChallanEntry>();
            _repository = repository ?? new ChallanRepository();
            _editingSr = -1;
            _isNewEntry = true;
            Result = new ChallanEntry { Date = System.DateTime.Today, AdvanceDate = System.DateTime.Today };
            DataContext = Result;
            LoadSuggestionSources();
            AutoFillNextChallanNumber(force: true);
        }

        public ChallanFormWindow(ChallanEntry existing, IEnumerable<ChallanEntry> allEntries, IChallanRepository repository = null)
        {
            InitializeComponent();
            ConfigureDebounceTimers();
            _allEntries = allEntries ?? new List<ChallanEntry>();
            _repository = repository ?? new ChallanRepository();
            _editingSr = existing.Sr;
            _isNewEntry = false;

            Result = new ChallanEntry
            {
                Id = existing.Id,
                Sr = existing.Sr,
                ChallanNumber = existing.ChallanNumber,
                Date = existing.Date,
                LRNumber = existing.LRNumber,
                BrokerName = existing.BrokerName,
                From = existing.From,
                To = existing.To,
                VehicleNumber = existing.VehicleNumber,
                VehicleType = existing.VehicleType,
                DriverName = existing.DriverName,
                DriverMobile = existing.DriverMobile,
                EngineNo = existing.EngineNo,
                LicenceNo = existing.LicenceNo,
                PolicyNo = existing.PolicyNo,
                ChassisNo = existing.ChassisNo,
                OwnerName = existing.OwnerName,
                PAN = existing.PAN,
                LorryHire = existing.LorryHire,
                LessTDS = existing.LessTDS,
                AdvanceAmount = existing.AdvanceAmount,
                AdvanceNEFT = existing.AdvanceNEFT,
                AdvanceCash = existing.AdvanceCash,
                AdvanceDate = existing.AdvanceDate,
                Detention = existing.Detention,
                Hamali = existing.Hamali,
                Deduction = existing.Deduction,
                BalancePaidNEFT = existing.BalancePaidNEFT,
                BalancePaidCash = existing.BalancePaidCash,
                BalancePaidDate = existing.BalancePaidDate,
                PaidTo = existing.PaidTo,
                Remarks = existing.Remarks,
                BillAmount = existing.BillAmount,
                Margin = existing.Margin
            };
            DataContext = Result;
            LoadSuggestionSources();
        }

        private void ConfigureDebounceTimers()
        {
            _vehicleSuggestionTimer.Tick += VehicleSuggestionTimer_Tick;
            Closed += (s, e) => _vehicleSuggestionTimer.Stop();
        }

        private void LoadSuggestionSources()
        {
            try
            {
                var entries = (_repository?.GetAll() ?? _allEntries ?? new List<ChallanEntry>())
                    .Where(x => x != null)
                    .ToList();

                _brokerNames = entries
                    .Select(x => (x.BrokerName ?? string.Empty).Trim())
                    .Where(x => !string.IsNullOrWhiteSpace(x))
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .OrderBy(x => x)
                    .ToList();

                _fromPlaces = entries
                    .Select(x => (x.From ?? string.Empty).Trim())
                    .Where(x => !string.IsNullOrWhiteSpace(x))
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .OrderBy(x => x)
                    .ToList();

                _toPlaces = entries
                    .Select(x => (x.To ?? string.Empty).Trim())
                    .Where(x => !string.IsNullOrWhiteSpace(x))
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .OrderBy(x => x)
                    .ToList();
            }
            catch
            {
                _brokerNames = new List<string>();
                _fromPlaces = new List<string>();
                _toPlaces = new List<string>();
            }
        }

        private void ChallanNo_LostFocus(object sender, RoutedEventArgs e)
        {
            NormalizeChallanNumberInForm();
            var num = ChallanNoBox?.Text?.Trim();
            if (string.IsNullOrWhiteSpace(num)) { ChallanDuplicateWarning.Visibility = Visibility.Collapsed; return; }
            try
            {
                var existing = _repository.FindByChallanNumber(num);
                ChallanDuplicateWarning.Visibility = (existing != null && existing.Sr != _editingSr) ? Visibility.Visible : Visibility.Collapsed;
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(ChallanNo_LostFocus), ex);
                ChallanDuplicateWarning.Visibility = Visibility.Collapsed;
            }
        }

        private void ChallanDatePicker_SelectedDateChanged(object sender, SelectionChangedEventArgs e)
        {
            AutoFillNextChallanNumber();
        }

        private void Save_Click(object sender, RoutedEventArgs e)
        {
            CommitDatePickerBindings();
            NormalizeChallanNumberInForm();
            if (string.IsNullOrWhiteSpace(Result.ChallanNumber))
            {
                MessageBox.Show("Challan Number cannot be empty.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.BrokerName))
            {
                MessageBox.Show("Agent / Broker is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.From))
            {
                MessageBox.Show("From is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.To))
            {
                MessageBox.Show("To is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            try
            {
                var dup = _repository.FindByChallanNumber(Result.ChallanNumber);
                if (dup != null && dup.Sr != _editingSr)
                {
                    MessageBox.Show($"Challan Number '{Result.ChallanNumber}' already exists.", "Duplicate Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(Save_Click), ex);
            }

            if (!string.IsNullOrWhiteSpace(Result.LRNumber))
            {
                var inputLRs = Result.LRNumber
                    .Split(new[] { ',', '\n', '\r' }, System.StringSplitOptions.RemoveEmptyEntries)
                    .Select(s => s.Trim())
                    .Where(s => !string.IsNullOrWhiteSpace(s))
                    .Distinct(System.StringComparer.OrdinalIgnoreCase)
                    .ToList();

                var entriesForValidation = (_repository?.GetAll() ?? _allEntries ?? new List<ChallanEntry>())
                    .Where(x => x != null && x.Sr != _editingSr && !string.IsNullOrWhiteSpace(x.LRNumber))
                    .ToList();

                foreach (var other in entriesForValidation)
                {
                    var otherLRs = (other.LRNumber ?? string.Empty)
                        .Split(new[] { ',', '\n', '\r' }, System.StringSplitOptions.RemoveEmptyEntries)
                        .Select(s => s.Trim());
                    var overlap = inputLRs.Intersect(otherLRs, System.StringComparer.OrdinalIgnoreCase).FirstOrDefault();
                    if (overlap != null)
                    {
                        MessageBox.Show($"LR Number '{overlap}' is already used in Challan '{other.ChallanNumber}'.", "Duplicate Error", MessageBoxButton.OK, MessageBoxImage.Error);
                        return;
                    }
                }
            }

            Result.RecalculateBalance();
            WasSaved = true;
            if (System.Windows.Interop.ComponentDispatcher.IsThreadModal)
            {
                DialogResult = true;
            }
            Close();
        }

        private void CommitDatePickerBindings()
        {
            UpdateDatePickerBinding(ChallanDatePicker);
            UpdateDatePickerBinding(AdvanceDatePicker);
            UpdateDatePickerBinding(BalancePaidDatePicker);
        }

        private static void UpdateDatePickerBinding(DatePicker picker)
        {
            if (picker == null) return;
            try
            {
                var binding = picker.GetBindingExpression(DatePicker.SelectedDateProperty);
                binding?.UpdateSource();
            }
            catch
            {
            }
        }

        private void NormalizeChallanNumberInForm()
        {
            if (Result == null)
            {
                return;
            }

            var normalized = ChallanNumberFormatter.Normalize(Result.ChallanNumber, Result.Date);
            if (!string.Equals(Result.ChallanNumber, normalized, System.StringComparison.Ordinal))
            {
                Result.ChallanNumber = normalized;
            }
        }

        private void AutoFillNextChallanNumber(bool force = false)
        {
            if (!_isNewEntry || Result == null)
            {
                return;
            }

            var current = (Result.ChallanNumber ?? string.Empty).Trim();
            if (!force &&
                current.Length > 0 &&
                !string.Equals(current, _lastAutoGeneratedChallanNumber, System.StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            var challanDate = Result.Date == default(System.DateTime)
                ? System.DateTime.Today
                : Result.Date;
            var nextNumber = BuildNextChallanNumber(challanDate);
            _lastAutoGeneratedChallanNumber = nextNumber;
            Result.ChallanNumber = nextNumber;
        }

        private string BuildNextChallanNumber(System.DateTime challanDate)
        {
            try
            {
                var fyStart = ChallanNumberFormatter.GetFinancialYearStart(challanDate);
                var challanLedgerRepository = new ChallanRepository { LedgerMode = "Challan" };
                var fySuffix = ChallanNumberFormatter.GetFinancialYearSuffix(challanDate);
                var latestRow = challanLedgerRepository
                    .SearchAdvanced(fySuffix, string.Empty, string.Empty, string.Empty, 1, 1, "ChallanNumber", false, true)
                    .FirstOrDefault();
                var nextSequence = latestRow != null &&
                                   ChallanNumberFormatter.GetFinancialYearStart(latestRow.ChallanNumber, latestRow.Date) == fyStart
                    ? ChallanNumberFormatter.GetSequence(latestRow.ChallanNumber) + 1
                    : 1;

                return ChallanNumberFormatter.Normalize(nextSequence.ToString(), challanDate);
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(BuildNextChallanNumber), ex);
                return ChallanNumberFormatter.Normalize("1", challanDate);
            }
        }

        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            WasSaved = false;
            if (System.Windows.Interop.ComponentDispatcher.IsThreadModal)
            {
                DialogResult = false;
            }
            Close();
        }

        private void VehicleNumberBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || VehicleNumberBox == null) return;
            var text = VehicleNumberBox.Text;
            if (string.IsNullOrWhiteSpace(text))
            {
                _vehicleSuggestionTimer.Stop();
                VehiclePopup.IsOpen = false;
                return;
            }
            _vehicleSuggestionTimer.Stop();
            _vehicleSuggestionTimer.Start();
        }

        private void VehicleSuggestionTimer_Tick(object sender, System.EventArgs e)
        {
            _vehicleSuggestionTimer.Stop();
            UpdateVehicleSuggestions();
        }

        private void UpdateVehicleSuggestions()
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || VehicleNumberBox == null) return;
            var text = VehicleNumberBox.Text;
            if (string.IsNullOrWhiteSpace(text))
            {
                VehiclePopup.IsOpen = false;
                return;
            }
            var matches = new VehicleRepository().SearchByVehicleNumber(text);
            _ignoreVehicleSelection = true;
            VehicleSuggestionList.ItemsSource = matches;
            if (matches.Count > 0) VehicleSuggestionList.SelectedIndex = 0;
            _ignoreVehicleSelection = false;
            VehiclePopup.IsOpen = matches.Count > 0;
        }

        private void VehicleSuggestionList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_ignoreVehicleSelection) return;
            var selected = VehicleSuggestionList?.SelectedItem as VehicleEntry;
            if (selected == null) return;
            ApplyVehicleSelection(selected);
            if (VehiclePopup != null) VehiclePopup.IsOpen = false;
        }

        private void VehicleSuggestionList_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            var dependencyObject = e.OriginalSource as DependencyObject;
            while (dependencyObject != null && !(dependencyObject is ListBoxItem))
            {
                dependencyObject = VisualTreeHelper.GetParent(dependencyObject);
            }

            var item = dependencyObject as ListBoxItem;
            if (item == null) return;

            var selected = item.DataContext as VehicleEntry;
            if (selected == null) return;

            VehicleSuggestionList.SelectedItem = selected;
            ApplyVehicleSelection(selected);
            if (VehiclePopup != null) VehiclePopup.IsOpen = false;
            e.Handled = true;
        }

        private void VehicleNumberBox_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || !VehiclePopup.IsOpen || VehicleSuggestionList.Items.Count == 0) return;
            if (e.Key == Key.Down)
            {
                e.Handled = true;
                if (VehicleSuggestionList.SelectedIndex < VehicleSuggestionList.Items.Count - 1)
                {
                    _ignoreVehicleSelection = true;
                    VehicleSuggestionList.SelectedIndex++;
                    _ignoreVehicleSelection = false;
                    VehicleSuggestionList.ScrollIntoView(VehicleSuggestionList.SelectedItem);
                }
            }
            else if (e.Key == Key.Up)
            {
                e.Handled = true;
                if (VehicleSuggestionList.SelectedIndex > 0)
                {
                    _ignoreVehicleSelection = true;
                    VehicleSuggestionList.SelectedIndex--;
                    _ignoreVehicleSelection = false;
                    VehicleSuggestionList.ScrollIntoView(VehicleSuggestionList.SelectedItem);
                }
            }
            else if (e.Key == Key.Enter)
            {
                e.Handled = true;
                var selected = VehicleSuggestionList.SelectedItem as VehicleEntry;
                if (selected != null) ApplyVehicleSelection(selected);
                VehiclePopup.IsOpen = false;
            }
            else if (e.Key == Key.Escape)
            {
                e.Handled = true;
                VehiclePopup.IsOpen = false;
            }
        }

        private void VehicleNumberBox_LostFocus(object sender, RoutedEventArgs e)
        {
            var vno = (Result?.VehicleNumber ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(vno)) return;
            var found = new VehicleRepository().FindByVehicleNumber(vno);
            if (found != null) ApplyVehicleSelection(found);
        }

        private void BrokerNameBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            UpdateTextSuggestions(BrokerNameBox, BrokerPopup, BrokerSuggestionList, _brokerNames);
        }

        private void FromBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            UpdateTextSuggestions(FromBox, FromPopup, FromSuggestionList, _fromPlaces);
        }

        private void ToBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            UpdateTextSuggestions(ToBox, ToPopup, ToSuggestionList, _toPlaces);
        }

        private void UpdateTextSuggestions(TextBox textBox, System.Windows.Controls.Primitives.Popup popup, ListBox listBox, IEnumerable<string> source)
        {
            if (_ignoreTextSuggestions || textBox == null || popup == null || listBox == null) return;

            var text = (textBox.Text ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(text))
            {
                popup.IsOpen = false;
                listBox.ItemsSource = null;
                return;
            }

            var matches = (source ?? Enumerable.Empty<string>())
                .Where(x => !string.IsNullOrWhiteSpace(x) &&
                            x.IndexOf(text, System.StringComparison.OrdinalIgnoreCase) >= 0 &&
                            !string.Equals(x.Trim(), text, System.StringComparison.OrdinalIgnoreCase))
                .Take(12)
                .ToList();

            listBox.ItemsSource = matches;
            listBox.SelectedIndex = matches.Count > 0 ? 0 : -1;
            popup.IsOpen = matches.Count > 0;
        }

        private void SuggestionTextBox_LostFocus(object sender, RoutedEventArgs e)
        {
            Dispatcher.BeginInvoke(new System.Action(() =>
            {
                if (BrokerPopup != null) BrokerPopup.IsOpen = false;
                if (FromPopup != null) FromPopup.IsOpen = false;
                if (ToPopup != null) ToPopup.IsOpen = false;
            }), DispatcherPriority.Background);
        }

        private void SuggestionTextBox_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            var textBox = sender as TextBox;
            if (textBox == null) return;

            System.Windows.Controls.Primitives.Popup popup;
            ListBox listBox;
            ResolveSuggestionControls(textBox, out popup, out listBox);
            if (popup == null || listBox == null || !popup.IsOpen || listBox.Items.Count == 0) return;

            if (e.Key == Key.Down)
            {
                if (listBox.SelectedIndex < listBox.Items.Count - 1)
                {
                    listBox.SelectedIndex++;
                    listBox.ScrollIntoView(listBox.SelectedItem);
                }
                e.Handled = true;
            }
            else if (e.Key == Key.Up)
            {
                if (listBox.SelectedIndex > 0)
                {
                    listBox.SelectedIndex--;
                    listBox.ScrollIntoView(listBox.SelectedItem);
                }
                e.Handled = true;
            }
            else if (e.Key == Key.Enter || e.Key == Key.Tab)
            {
                var selected = listBox.SelectedItem as string;
                if (!string.IsNullOrWhiteSpace(selected))
                {
                    ApplySuggestion(textBox, popup, selected);
                    e.Handled = true;
                }
            }
            else if (e.Key == Key.Escape)
            {
                popup.IsOpen = false;
                e.Handled = true;
            }
        }

        private void BrokerSuggestionList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_ignoreTextSuggestions) return;
        }

        private void FromSuggestionList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_ignoreTextSuggestions) return;
        }

        private void ToSuggestionList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_ignoreTextSuggestions) return;
        }

        private void SuggestionList_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            var listBox = sender as ListBox;
            if (listBox == null) return;

            var dependencyObject = e.OriginalSource as DependencyObject;
            while (dependencyObject != null && !(dependencyObject is ListBoxItem))
            {
                dependencyObject = VisualTreeHelper.GetParent(dependencyObject);
            }

            var item = dependencyObject as ListBoxItem;
            if (item == null) return;

            var selected = item.DataContext as string;
            if (string.IsNullOrWhiteSpace(selected)) return;

            if (ReferenceEquals(listBox, BrokerSuggestionList))
            {
                ApplySuggestion(BrokerNameBox, BrokerPopup, selected);
            }
            else if (ReferenceEquals(listBox, FromSuggestionList))
            {
                ApplySuggestion(FromBox, FromPopup, selected);
            }
            else if (ReferenceEquals(listBox, ToSuggestionList))
            {
                ApplySuggestion(ToBox, ToPopup, selected);
            }

            e.Handled = true;
        }

        private void ResolveSuggestionControls(TextBox textBox, out System.Windows.Controls.Primitives.Popup popup, out ListBox listBox)
        {
            popup = null;
            listBox = null;

            if (ReferenceEquals(textBox, BrokerNameBox))
            {
                popup = BrokerPopup;
                listBox = BrokerSuggestionList;
            }
            else if (ReferenceEquals(textBox, FromBox))
            {
                popup = FromPopup;
                listBox = FromSuggestionList;
            }
            else if (ReferenceEquals(textBox, ToBox))
            {
                popup = ToPopup;
                listBox = ToSuggestionList;
            }
        }

        private void ApplySuggestion(TextBox textBox, System.Windows.Controls.Primitives.Popup popup, string value)
        {
            if (textBox == null) return;

            _ignoreTextSuggestions = true;
            try
            {
                textBox.Text = value ?? string.Empty;
                textBox.CaretIndex = textBox.Text.Length;
                if (popup != null) popup.IsOpen = false;
            }
            finally
            {
                _ignoreTextSuggestions = false;
            }
        }

        private void ApplyVehicleSelection(VehicleEntry v)
        {
            if (Result == null || v == null) return;
            Result.VehicleNumber = (v.VehicleNumber ?? string.Empty).Trim().ToUpperInvariant();
            Result.OwnerName = v.OwnerName;
            Result.PAN = v.PANNumber;
            Result.EngineNo = v.EngineNumber;
            Result.ChassisNo = v.ChassisNumber;
            Result.VehicleType = v.VehicleType;
            Result.DriverName = v.DriverName;
            Result.DriverMobile = v.DriverMobile;
            Result.LicenceNo = v.LicenceNumber;
            Result.PolicyNo = v.PolicyNumber;
        }

        private void CurrencyTextBox_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (sender is TextBox tb && !tb.IsKeyboardFocusWithin)
            {
                e.Handled = true;
                tb.Focus();
            }
        }

        private void CurrencyTextBox_GotKeyboardFocus(object sender, KeyboardFocusChangedEventArgs e)
        {
            var tb = sender as TextBox;
            if (tb == null) return;
            if (IsZeroLike(tb.Text))
            {
                tb.SelectAll();
            }
        }

        private static bool IsZeroLike(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return true;
            var cleaned = text.Replace("Rs.", "").Replace(",", "").Trim();
            if (decimal.TryParse(cleaned, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v))
            {
                return v == 0m;
            }
            if (decimal.TryParse(cleaned, out v))
            {
                return v == 0m;
            }
            return false;
        }
    }
}
