using System.Collections.Generic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Threading;
using Awagaman_ERP.Data;
using Awagaman_ERP.Helpers;
using Awagaman_ERP.Models;
using MahApps.Metro.Controls;

namespace Awagaman_ERP
{
    public partial class ChallanFormWindow : MetroWindow
    {
        public ChallanEntry Result { get; private set; }
        public bool WasSaved { get; private set; }
        private IEnumerable<ChallanEntry> _allEntries;
        private int _editingSr;
        private readonly IChallanRepository _repository;
        private bool _ignoreVehicleSelection;
        private readonly bool _isNewEntry;
        private string _lastAutoGeneratedChallanNumber = string.Empty;
        private string _lastAutoGeneratedLrNumber = string.Empty;
        private readonly DispatcherTimer _vehicleSuggestionTimer = new DispatcherTimer { Interval = System.TimeSpan.FromMilliseconds(350) };

        public ChallanFormWindow(IEnumerable<ChallanEntry> allEntries, IChallanRepository repository = null)
        {
            InitializeComponent();
            ConfigureDebounceTimers();
            _allEntries = allEntries ?? new List<ChallanEntry>();
            _repository = repository ?? new ChallanRepository();
            _editingSr = -1;
            _isNewEntry = true;
            Result = new ChallanEntry { Date = System.DateTime.Today, AdvanceDate = System.DateTime.Today };
            DataContext = Result;
            AutoFillNextChallanNumber(force: true);
            AutoFillNextLrNumber(force: true);
        }

        public ChallanFormWindow(ChallanEntry existing, IEnumerable<ChallanEntry> allEntries, IChallanRepository repository = null)
        {
            InitializeComponent();
            ConfigureDebounceTimers();
            _allEntries = allEntries ?? new List<ChallanEntry>();
            _repository = repository ?? new ChallanRepository();
            _editingSr = existing.Sr;
            _isNewEntry = false;

            Result = new ChallanEntry
            {
                Id = existing.Id,
                Sr = existing.Sr,
                ChallanNumber = existing.ChallanNumber,
                Date = existing.Date,
                LRNumber = existing.LRNumber,
                BrokerName = existing.BrokerName,
                From = existing.From,
                To = existing.To,
                VehicleNumber = existing.VehicleNumber,
                VehicleType = existing.VehicleType,
                DriverName = existing.DriverName,
                DriverMobile = existing.DriverMobile,
                EngineNo = existing.EngineNo,
                LicenceNo = existing.LicenceNo,
                PolicyNo = existing.PolicyNo,
                ChassisNo = existing.ChassisNo,
                OwnerName = existing.OwnerName,
                PAN = existing.PAN,
                LorryHire = existing.LorryHire,
                LessTDS = existing.LessTDS,
                AdvanceAmount = existing.AdvanceAmount,
                AdvanceNEFT = existing.AdvanceNEFT,
                AdvanceCash = existing.AdvanceCash,
                AdvanceDate = existing.AdvanceDate,
                Detention = existing.Detention,
                Hamali = existing.Hamali,
                Deduction = existing.Deduction,
                BalancePaidNEFT = existing.BalancePaidNEFT,
                BalancePaidCash = existing.BalancePaidCash,
                BalancePaidDate = existing.BalancePaidDate,
                PaidTo = existing.PaidTo,
                Remarks = existing.Remarks,
                BillAmount = existing.BillAmount,
                Margin = existing.Margin
            };
            DataContext = Result;
        }

        private void ConfigureDebounceTimers()
        {
            _vehicleSuggestionTimer.Tick += VehicleSuggestionTimer_Tick;
            Closed += (s, e) => _vehicleSuggestionTimer.Stop();
        }

        private void ChallanNo_LostFocus(object sender, RoutedEventArgs e)
        {
            NormalizeChallanNumberInForm();
            var num = ChallanNoBox?.Text?.Trim();
            if (string.IsNullOrWhiteSpace(num)) { ChallanDuplicateWarning.Visibility = Visibility.Collapsed; return; }
            try
            {
                var existing = _repository.FindByChallanNumber(num);
                ChallanDuplicateWarning.Visibility = (existing != null && existing.Sr != _editingSr) ? Visibility.Visible : Visibility.Collapsed;
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(ChallanNo_LostFocus), ex);
                ChallanDuplicateWarning.Visibility = Visibility.Collapsed;
            }
        }

        private void ChallanDatePicker_SelectedDateChanged(object sender, SelectionChangedEventArgs e)
        {
            AutoFillNextChallanNumber();
        }

        private void Save_Click(object sender, RoutedEventArgs e)
        {
            NormalizeChallanNumberInForm();
            if (string.IsNullOrWhiteSpace(Result.ChallanNumber))
            {
                MessageBox.Show("Challan Number cannot be empty.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.BrokerName))
            {
                MessageBox.Show("Agent / Broker is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.From))
            {
                MessageBox.Show("From is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(Result.To))
            {
                MessageBox.Show("To is mandatory.", "Validation Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            try
            {
                var dup = _repository.FindByChallanNumber(Result.ChallanNumber);
                if (dup != null && dup.Sr != _editingSr)
                {
                    MessageBox.Show($"Challan Number '{Result.ChallanNumber}' already exists.", "Duplicate Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(Save_Click), ex);
            }

            if (!string.IsNullOrWhiteSpace(Result.LRNumber))
            {
                var inputLRs = Result.LRNumber.Split(new[] { ',', '\n', '\r' }, System.StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim()).ToList();
                foreach (var other in _allEntries.Where(x => x.Sr != _editingSr && !string.IsNullOrWhiteSpace(x.LRNumber)))
                {
                    var otherLRs = other.LRNumber.Split(new[] { ',', '\n', '\r' }, System.StringSplitOptions.RemoveEmptyEntries).Select(s => s.Trim());
                    var overlap = inputLRs.Intersect(otherLRs, System.StringComparer.OrdinalIgnoreCase).FirstOrDefault();
                    if (overlap != null)
                    {
                        MessageBox.Show($"LR Number '{overlap}' is already used in Challan '{other.ChallanNumber}'.", "Duplicate Error", MessageBoxButton.OK, MessageBoxImage.Error);
                        return;
                    }
                }
            }

            Result.RecalculateBalance();
            WasSaved = true;
            if (System.Windows.Interop.ComponentDispatcher.IsThreadModal)
            {
                DialogResult = true;
            }
            Close();
        }

        private void NormalizeChallanNumberInForm()
        {
            if (Result == null)
            {
                return;
            }

            var normalized = ChallanNumberFormatter.Normalize(Result.ChallanNumber, Result.Date);
            if (!string.Equals(Result.ChallanNumber, normalized, System.StringComparison.Ordinal))
            {
                Result.ChallanNumber = normalized;
            }
        }

        private void AutoFillNextChallanNumber(bool force = false)
        {
            if (!_isNewEntry || Result == null)
            {
                return;
            }

            var current = (Result.ChallanNumber ?? string.Empty).Trim();
            if (!force &&
                current.Length > 0 &&
                !string.Equals(current, _lastAutoGeneratedChallanNumber, System.StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            var challanDate = Result.Date == default(System.DateTime)
                ? System.DateTime.Today
                : Result.Date;
            var nextNumber = BuildNextChallanNumber(challanDate);
            _lastAutoGeneratedChallanNumber = nextNumber;
            Result.ChallanNumber = nextNumber;
        }

        private void AutoFillNextLrNumber(bool force = false)
        {
            if (!_isNewEntry || Result == null)
            {
                return;
            }

            var current = (Result.LRNumber ?? string.Empty).Trim();
            if (!force &&
                current.Length > 0 &&
                !string.Equals(current, _lastAutoGeneratedLrNumber, System.StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            var nextNumber = BuildNextLrNumber();
            _lastAutoGeneratedLrNumber = nextNumber;
            Result.LRNumber = nextNumber;
        }

        private string BuildNextChallanNumber(System.DateTime challanDate)
        {
            try
            {
                var fyStart = ChallanNumberFormatter.GetFinancialYearStart(challanDate);
                var challanLedgerRepository = new ChallanRepository { LedgerMode = "Challan" };
                var rows = challanLedgerRepository.GetAll() ?? new List<ChallanEntry>();
                var nextSequence = rows
                    .Where(x => x != null)
                    .Where(x => ChallanNumberFormatter.GetFinancialYearStart(x.ChallanNumber, x.Date) == fyStart)
                    .Select(x => ChallanNumberFormatter.GetSequence(x.ChallanNumber))
                    .DefaultIfEmpty(0)
                    .Max() + 1;

                return ChallanNumberFormatter.Normalize(nextSequence.ToString(), challanDate);
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(BuildNextChallanNumber), ex);
                return ChallanNumberFormatter.Normalize("1", challanDate);
            }
        }

        private string BuildNextLrNumber()
        {
            try
            {
                var lrRepository = new LRRepository();
                var latest = (lrRepository.GetPage(1, 1, "LRNo", false) ?? new List<LREntry>())
                    .FirstOrDefault();
                var latestLrNo = (latest?.LRNo ?? string.Empty).Trim();
                if (string.IsNullOrWhiteSpace(latestLrNo))
                {
                    return "1";
                }

                var slashIndex = latestLrNo.IndexOf('/');
                var prefix = slashIndex > 0 ? latestLrNo.Substring(0, slashIndex).Trim() : latestLrNo;
                var suffix = slashIndex > 0 && slashIndex < latestLrNo.Length - 1
                    ? latestLrNo.Substring(slashIndex + 1).Trim()
                    : string.Empty;
                var digits = new string(prefix.Where(char.IsDigit).ToArray());
                var nextSequence = int.TryParse(digits, out var parsed) ? parsed + 1 : 1;

                return string.IsNullOrWhiteSpace(suffix)
                    ? nextSequence.ToString()
                    : nextSequence + "/" + suffix;
            }
            catch (System.Exception ex)
            {
                AppLogger.LogException(nameof(BuildNextLrNumber), ex);
                return "1";
            }
        }

        private void Cancel_Click(object sender, RoutedEventArgs e)
        {
            WasSaved = false;
            if (System.Windows.Interop.ComponentDispatcher.IsThreadModal)
            {
                DialogResult = false;
            }
            Close();
        }

        private void VehicleNumberBox_TextChanged(object sender, TextChangedEventArgs e)
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || VehicleNumberBox == null) return;
            var text = VehicleNumberBox.Text;
            if (string.IsNullOrWhiteSpace(text))
            {
                _vehicleSuggestionTimer.Stop();
                VehiclePopup.IsOpen = false;
                return;
            }
            _vehicleSuggestionTimer.Stop();
            _vehicleSuggestionTimer.Start();
        }

        private void VehicleSuggestionTimer_Tick(object sender, System.EventArgs e)
        {
            _vehicleSuggestionTimer.Stop();
            UpdateVehicleSuggestions();
        }

        private void UpdateVehicleSuggestions()
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || VehicleNumberBox == null) return;
            var text = VehicleNumberBox.Text;
            if (string.IsNullOrWhiteSpace(text))
            {
                VehiclePopup.IsOpen = false;
                return;
            }
            var matches = new VehicleRepository().SearchByVehicleNumber(text);
            _ignoreVehicleSelection = true;
            VehicleSuggestionList.ItemsSource = matches;
            if (matches.Count > 0) VehicleSuggestionList.SelectedIndex = 0;
            _ignoreVehicleSelection = false;
            VehiclePopup.IsOpen = matches.Count > 0;
        }

        private void VehicleSuggestionList_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_ignoreVehicleSelection) return;
            var selected = VehicleSuggestionList?.SelectedItem as VehicleEntry;
            if (selected == null) return;
            ApplyVehicleSelection(selected);
            if (VehiclePopup != null) VehiclePopup.IsOpen = false;
        }

        private void VehicleNumberBox_PreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (VehiclePopup == null || VehicleSuggestionList == null || !VehiclePopup.IsOpen || VehicleSuggestionList.Items.Count == 0) return;
            if (e.Key == Key.Down)
            {
                e.Handled = true;
                if (VehicleSuggestionList.SelectedIndex < VehicleSuggestionList.Items.Count - 1)
                {
                    _ignoreVehicleSelection = true;
                    VehicleSuggestionList.SelectedIndex++;
                    _ignoreVehicleSelection = false;
                    VehicleSuggestionList.ScrollIntoView(VehicleSuggestionList.SelectedItem);
                }
            }
            else if (e.Key == Key.Up)
            {
                e.Handled = true;
                if (VehicleSuggestionList.SelectedIndex > 0)
                {
                    _ignoreVehicleSelection = true;
                    VehicleSuggestionList.SelectedIndex--;
                    _ignoreVehicleSelection = false;
                    VehicleSuggestionList.ScrollIntoView(VehicleSuggestionList.SelectedItem);
                }
            }
            else if (e.Key == Key.Enter)
            {
                e.Handled = true;
                var selected = VehicleSuggestionList.SelectedItem as VehicleEntry;
                if (selected != null) ApplyVehicleSelection(selected);
                VehiclePopup.IsOpen = false;
            }
            else if (e.Key == Key.Escape)
            {
                e.Handled = true;
                VehiclePopup.IsOpen = false;
            }
        }

        private void VehicleNumberBox_LostFocus(object sender, RoutedEventArgs e)
        {
            var vno = (Result?.VehicleNumber ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(vno)) return;
            var found = new VehicleRepository().FindByVehicleNumber(vno);
            if (found != null) ApplyVehicleSelection(found);
        }

        private void ApplyVehicleSelection(VehicleEntry v)
        {
            if (Result == null || v == null) return;
            Result.VehicleNumber = (v.VehicleNumber ?? string.Empty).Trim().ToUpperInvariant();
            Result.OwnerName = v.OwnerName;
            Result.PAN = v.PANNumber;
            Result.EngineNo = v.EngineNumber;
            Result.ChassisNo = v.ChassisNumber;
            Result.VehicleType = v.VehicleType;
            Result.DriverName = v.DriverName;
            Result.DriverMobile = v.DriverMobile;
            Result.LicenceNo = v.LicenceNumber;
            Result.PolicyNo = v.PolicyNumber;
        }

        private void CurrencyTextBox_PreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (sender is TextBox tb && !tb.IsKeyboardFocusWithin)
            {
                e.Handled = true;
                tb.Focus();
            }
        }

        private void CurrencyTextBox_GotKeyboardFocus(object sender, KeyboardFocusChangedEventArgs e)
        {
            var tb = sender as TextBox;
            if (tb == null) return;
            if (IsZeroLike(tb.Text))
            {
                tb.SelectAll();
            }
        }

        private static bool IsZeroLike(string text)
        {
            if (string.IsNullOrWhiteSpace(text)) return true;
            var cleaned = text.Replace("Rs.", "").Replace(",", "").Trim();
            if (decimal.TryParse(cleaned, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var v))
            {
                return v == 0m;
            }
            if (decimal.TryParse(cleaned, out v))
            {
                return v == 0m;
            }
            return false;
        }
    }
}
